version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
  
jobs:
  build:
    docker:
      - image: '********** CHANGE ME 1 **********'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: '********** CHANGE ME 2 **********'
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
